### ISSUE TITLE
File not exist?

### ISSUE THREAD

**Issue by elfeffe** [mageplaza/magento-2-image-optimizer#4]
I'm having errors like 
file pub/media/wysiwyg/Product_images/Filters/CPL/Arand-Taquet-9.jpg does not exist

But it exists
And they optimize using php bin/ magento mpimageoptimizer:optimize

I'm using PHP7.3, and the same extensions are in CLI and FPM

**Comment by Tuvpt** [comment]
https://github.com/mageplaza/magento-2-image-optimizer/pull/10#issue-410665010
