### ISSUE TITLE
Convert images to webp

### ISSUE THREAD

**Issue by rakibabu** [mageplaza/magento-2-image-optimizer#6]
Hi Mageplaza,

Can we use this module with the same jobs to convert jpg,png etc async to webp and integrate this module: https://github.com/yireo/Yireo_Webp2 for support for webp? 

Happy to hear ;)

**Comment by Tuvpt** [comment]
@rakibabu Thank you for your interest in our module.
Currently, the module does not have image conversion function and it does not support for webp yet
