### ISSUE TITLE
Typo in optimize cli command

### ISSUE THREAD

**Issue by balasivagnanam** [mageplaza/magento-2-image-optimizer#9]
`php bin/ magento mpimageoptimizer: optimize`

update to 

`php bin/magento mpimageoptimizer:optimize`

**Comment by toandt98** [comment]
Good week, Balasivagnanam
First of all, thank you for contacting us. I'm Uri from Mageplaza Support Team.

I have received your information. 
Regarding the Image Optimize module, you can use the following commands:
- Scan command: php bin/magento mpimageoptimizer:scan
- Optimize command: php bin/magento mpimageoptimizer:optimize

Best Regards,
​Uri

**Comment by Tuvpt** [comment]
@balasivagnanam Thank you for your interest in our module,
We have revised the typo on the user guide
